name: Deploy dokku

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to dokku
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure the full history is fetched

      - name: Deploy
        id: deploy
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.DOKKU_SSH_KEY }}
          dokku-host: 'soulmate.pro.et'
          app-name: 'math'
          remote-branch: 'main'
