name: Deploy dokku

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.DOKKU_SSH_KEY }}
          dokku-host: 'soulmate.pro.et'
          app-name: 'math'
          remote-branch: 'main'
